apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cuseum-data
  namespace: cuseum
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
