apiVersion: v1
kind: Secret
metadata:
  name: cuseum-env
  namespace: cuseum
type: Opaque
stringData:
  BETTER_AUTH_SECRET: "REPLACE_ME_BETTER_AUTH_SECRET"
  CURATOR_SETUP_SECRET: "REPLACE_ME_CURATOR_SETUP_SECRET"
